name: DoorBell
main: DataLion\DoorBell\Main
version: 0.0.1
api: 3.0.0

author: DataLion

description: Super Simple Doorbell plugin

commands:
 createdoorbell:
  permission: createdoorbell.command
  description: Create a doorbell


permissions:
 createdoorbell.command:
  description: Create a doorbell perm



